"""
ZANTARA RAG - Services

Backward-compatible re-exports for all services after reorganization.
All services can still be imported from services.X for compatibility.
"""

# Search services
from .search.search_service import SearchService
from .search.search_filters import build_search_filter
from .search.semantic_cache import SemanticCache
from .search.citation_service import CitationService

# Memory services
from .memory import (
    MemoryOrchestrator,
    MemoryContext,
    MemoryFact,
    MemoryStats,
    MemoryProcessResult,
    FactType,
    MemoryFactExtractor,
    InMemoryConversationCache,
    get_memory_cache,
    MemoryServicePostgres,
    UserMemory,
    EpisodicMemoryService,
    EventType,
    Emotion,
    CollectiveMemoryService,
    CollectiveMemory,
    CollectiveMemoryEmitter,
    MemoryCategory,
    CollectiveMemoryState,
    create_collective_memory_workflow,
)

# Oracle services
from .oracle import (
    OracleService,
    OracleConfiguration,
    oracle_config,
    DatabaseManager,
    db_manager,
    GoogleServices,
    google_services,
    detect_query_language,
    generate_query_hash,
    smart_oracle,
    download_pdf_from_drive,
    get_drive_service,
    test_drive_connection,
    CrossOracleSynthesisService,
    OracleQuery,
    SynthesisResult,
    LanguageDetectionService,
    UserContextService,
    ReasoningEngineService,
    DocumentRetrievalService,
    OracleAnalyticsService,
)

# Routing services
from .routing import (
    QueryRouter,
    QueryRouterIntegration,
    IntelligentRouter,
    GoldenRouterService,
    ConflictResolver,
    KeywordMatcherService,
    ConfidenceCalculatorService,
    FallbackManagerService,
    PriorityOverrideService,
    RoutingStatsService,
)

# CRM services
from .crm import (
    AutoCRMService,
    get_auto_crm_service,
    AICRMExtractor,
    get_extractor,
    CollaboratorService,
    CollaboratorProfile,
)

# Ingestion services
from .ingestion import (
    IngestionService,
    CollectionManager,
    CollectionHealthService,
    HealthStatus,
    StalenessSeverity,
    CollectionMetrics,
    CollectionWarmupService,
    LegalIngestionService,
    AutoIngestionOrchestrator,
    SourceType,
    UpdateType,
    IngestionStatus,
    MonitoredSource,
    ScrapedContent,
    IngestionJob,
    PoliticsIngestionService,
)

# LLM client services
from .llm_clients import (
    GeminiService,
    GeminiJakselService,
    DeepSeekClient,
    DeepSeekResponse,
    OpenRouterClient,
    ModelTier,
    CompletionResult,
    VertexAIService,
)

# Pricing services
from .pricing import (
    PricingService,
    get_pricing_service,
    get_all_prices,
    search_service as pricing_search_service,
    get_visa_prices,
    get_kitas_prices,
    get_business_prices,
    get_tax_prices,
    get_pricing_context_for_llm,
    DynamicPricingService,
)

# Monitoring services
from .monitoring import (
    HealthMonitor,
    get_health_monitor,
    init_health_monitor,
    AlertService,
    AlertLevel,
    get_alert_service,
    AuditService,
    get_audit_service,
    UnifiedHealthService,
    get_unified_health_service,
    HealthCheckResult,
    SystemMetrics,
)

# Analytics services
from .analytics import (
    AnalyticsAggregator,
    TeamAnalyticsService,
    TeamTimesheetService,
    get_timesheet_service,
    init_timesheet_service,
    PatternAnalyzerService,
    ProductivityScorerService,
    BurnoutDetectorService,
    PerformanceTrendService,
    WorkloadBalanceService,
    OptimalHoursService,
    TeamInsightsService,
)

# Misc services
from .misc import (
    ClarificationService,
    ContextSuggestionService,
    get_context_suggestion_service,
    AdvancedContextWindowManager,
    ConversationService,
    CulturalInsightsService,
    CulturalRAGService,
    EmotionalAttunementService,
    FollowupService,
    GoldenAnswerService,
    GraphExtractor,
    GraphService,
    ImageGenerationService,
    KnowledgeGraphBuilder,
    Entity,
    EntityType,
    Relationship,
    RelationType,
    MCPClientService,
    MigrationRunner,
    PerformanceMonitor,
    PersonalityService,
    ProactiveComplianceMonitor,
    format_search_results,
    SessionService,
    ToolExecutor,
    WorkSessionService,
    ZantaraTools,
    get_zantara_tools,
    AutonomousResearchService,
    AutonomousScheduler,
    ClientJourneyOrchestrator,
)

__all__ = [
    # Search
    "SearchService",
    "build_search_filter",
    "SemanticCache",
    "CitationService",
    # Memory
    "MemoryOrchestrator",
    "MemoryContext",
    "MemoryFact",
    "MemoryStats",
    "MemoryProcessResult",
    "FactType",
    "MemoryFactExtractor",
    "InMemoryConversationCache",
    "get_memory_cache",
    "MemoryServicePostgres",
    "UserMemory",
    "EpisodicMemoryService",
    "EventType",
    "Emotion",
    "CollectiveMemoryService",
    "CollectiveMemory",
    "CollectiveMemoryEmitter",
    "MemoryCategory",
    "CollectiveMemoryState",
    "create_collective_memory_workflow",
    # Oracle
    "OracleService",
    "OracleConfiguration",
    "oracle_config",
    "DatabaseManager",
    "db_manager",
    "GoogleServices",
    "google_services",
    "detect_query_language",
    "generate_query_hash",
    "smart_oracle",
    "download_pdf_from_drive",
    "get_drive_service",
    "test_drive_connection",
    "CrossOracleSynthesisService",
    "OracleQuery",
    "SynthesisResult",
    "LanguageDetectionService",
    "UserContextService",
    "ReasoningEngineService",
    "DocumentRetrievalService",
    "OracleAnalyticsService",
    # Routing
    "QueryRouter",
    "QueryRouterIntegration",
    "IntelligentRouter",
    "GoldenRouterService",
    "ConflictResolver",
    "KeywordMatcherService",
    "ConfidenceCalculatorService",
    "FallbackManagerService",
    "PriorityOverrideService",
    "RoutingStatsService",
    # CRM
    "AutoCRMService",
    "get_auto_crm_service",
    "AICRMExtractor",
    "get_extractor",
    "CollaboratorService",
    "CollaboratorProfile",
    # Ingestion
    "IngestionService",
    "CollectionManager",
    "CollectionHealthService",
    "HealthStatus",
    "StalenessSeverity",
    "CollectionMetrics",
    "CollectionWarmupService",
    "LegalIngestionService",
    "AutoIngestionOrchestrator",
    "SourceType",
    "UpdateType",
    "IngestionStatus",
    "MonitoredSource",
    "ScrapedContent",
    "IngestionJob",
    "PoliticsIngestionService",
    # LLM Clients
    "GeminiService",
    "GeminiJakselService",
    "DeepSeekClient",
    "DeepSeekResponse",
    "OpenRouterClient",
    "ModelTier",
    "CompletionResult",
    "VertexAIService",
    # Pricing
    "PricingService",
    "get_pricing_service",
    "get_all_prices",
    "pricing_search_service",
    "get_visa_prices",
    "get_kitas_prices",
    "get_business_prices",
    "get_tax_prices",
    "get_pricing_context_for_llm",
    "DynamicPricingService",
    # Monitoring
    "HealthMonitor",
    "get_health_monitor",
    "init_health_monitor",
    "AlertService",
    "AlertLevel",
    "get_alert_service",
    "AuditService",
    "get_audit_service",
    "UnifiedHealthService",
    "get_unified_health_service",
    "HealthCheckResult",
    "SystemMetrics",
    # Analytics
    "AnalyticsAggregator",
    "TeamAnalyticsService",
    "TeamTimesheetService",
    "get_timesheet_service",
    "init_timesheet_service",
    "PatternAnalyzerService",
    "ProductivityScorerService",
    "BurnoutDetectorService",
    "PerformanceTrendService",
    "WorkloadBalanceService",
    "OptimalHoursService",
    "TeamInsightsService",
    # Misc
    "ClarificationService",
    "ContextSuggestionService",
    "get_context_suggestion_service",
    "AdvancedContextWindowManager",
    "ConversationService",
    "CulturalInsightsService",
    "CulturalRAGService",
    "EmotionalAttunementService",
    "FollowupService",
    "GoldenAnswerService",
    "GraphExtractor",
    "GraphService",
    "ImageGenerationService",
    "KnowledgeGraphBuilder",
    "Entity",
    "EntityType",
    "Relationship",
    "RelationType",
    "MCPClientService",
    "MigrationRunner",
    "PerformanceMonitor",
    "PersonalityService",
    "ProactiveComplianceMonitor",
    "format_search_results",
    "SessionService",
    "ToolExecutor",
    "WorkSessionService",
    "ZantaraTools",
    "get_zantara_tools",
    "AutonomousResearchService",
    "AutonomousScheduler",
    "ClientJourneyOrchestrator",
]
