#!/usr/bin/env python3
"""
CRM Stress Test & Load Generator
Simulates massive client and case creation to verify database resilience.

Usage:
    python3 scripts/stress_test_crm.py --url https://nuzantara-rag.fly.dev --key YOUR_KEY
    python3 scripts/stress_test_crm.py --local (uses http://localhost:8080)
"""

import argparse
import asyncio
import logging
import os
import random
import sys
import time
import uuid

import httpx

# Configuration Defaults
DEFAULT_URL = "http://localhost:8080"
DEFAULT_KEY = os.getenv("API_KEY")

if not DEFAULT_KEY:
    print("❌ ERROR: API_KEY environment variable is required")
    print("   Set it with: export API_KEY=your_api_key")
    print("   Or use --key argument")
    sys.exit(1)

# Logging Setup
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger("crm_load_test")


class CRMStressTester:
    def __init__(self, base_url: str, api_key: str, concurrency: int = 5):
        self.base_url = base_url.rstrip("/")
        self.headers = {
            "X-API-Key": api_key,
            "Content-Type": "application/json",
            "User-Agent": "Nuzantara-StressTest/1.0",
        }
        self.concurrency = concurrency
        self.semaphore = asyncio.Semaphore(concurrency)
        self.stats = {
            "clients_created": 0,
            "clients_failed": 0,
            "cases_created": 0,
            "cases_failed": 0,
            "errors": [],
            "latencies": [],
        }

    def _random_string(self, length=8) -> str:
        return uuid.uuid4().hex[:length]

    def _generate_client(self) -> dict:
        uid = self._random_string()
        return {
            "full_name": f"LoadTest User {uid}",
            "email": f"load.{uid}@example.com",
            "phone": f"+628{random.randint(100000000, 999999999)}",
            "nationality": random.choice(["Italian", "French", "Australian", "American", "German"]),
            "status": random.choice(["lead", "active", "inactive"]),
            "client_type": random.choice(["individual", "company"]),
            "company_name": f"PT LoadTest {uid} Tbk" if random.random() > 0.5 else None,
            "address": "Jalan Stress Test No. 1, Bali",
            "notes": "Generated by stress test script",
        }

    def _generate_practice(self, client_id: int) -> dict:
        types = ["kitas_application", "pt_pma_setup", "tax_consulting", "visa_extension"]
        return {
            "client_id": client_id,
            "practice_type_code": random.choice(types),
            "status": random.choice(["inquiry", "quotation_sent", "in_progress", "completed"]),
            "notes": f"Load Test Case {self._random_string()}",
            "priority": random.choice(["normal", "high", "urgent"]),
        }

    async def _post(self, client: httpx.AsyncClient, endpoint: str, data: dict) -> dict:
        start = time.time()
        try:
            async with self.semaphore:
                response = await client.post(
                    f"{self.base_url}{endpoint}?created_by=stress_bot",
                    json=data,
                    headers=self.headers,
                )
                duration = time.time() - start

                self.stats["latencies"].append(duration)

                if response.status_code in [200, 201]:
                    return {"success": True, "data": response.json(), "duration": duration}
                else:
                    error_msg = f"{response.status_code}: {response.text}"
                    self.stats["errors"].append(error_msg)
                    return {"success": False, "error": error_msg}
        except Exception as e:
            self.stats["errors"].append(str(e))
            return {"success": False, "error": str(e)}

    async def run(self, num_clients: int, cases_per_client: int):
        logger.info(f"🚀 Starting Load Test against {self.base_url}")
        logger.info(f"🎯 Target: {num_clients} Clients, {num_clients * cases_per_client} Cases")

        async with httpx.AsyncClient(timeout=30.0) as client:
            # 1. Health Check
            try:
                resp = await client.get(f"{self.base_url}/health")
                if resp.status_code != 200:
                    logger.error(f"❌ Health check failed: {resp.status_code}")
                    return
                logger.info("✅ Health check passed")
            except Exception as e:
                logger.critical(f"❌ Connection failed: {e}")
                return

            # 2. Create Clients
            start_time = time.time()
            client_tasks = []
            for _ in range(num_clients):
                client_tasks.append(self._post(client, "/api/crm/clients", self._generate_client()))

            client_results = await asyncio.gather(*client_tasks)

            created_client_ids = []
            for res in client_results:
                if res["success"]:
                    self.stats["clients_created"] += 1
                    created_client_ids.append(res["data"]["id"])
                else:
                    self.stats["clients_failed"] += 1

            logger.info(f"✅ Created {len(created_client_ids)} clients. Starting cases...")

            # 3. Create Cases
            case_tasks = []
            for client_id in created_client_ids:
                for _ in range(cases_per_client):
                    case_tasks.append(
                        self._post(
                            client, "/api/crm/practices/", self._generate_practice(client_id)
                        )
                    )

            case_results = await asyncio.gather(*case_tasks)

            for res in case_results:
                if res["success"]:
                    self.stats["cases_created"] += 1
                else:
                    self.stats["cases_failed"] += 1

            total_time = time.time() - start_time
            self._print_report(total_time)

    def _print_report(self, total_time: float):
        print("\n" + "=" * 50)
        print("📊 STRESS TEST REPORT")
        print("=" * 50)
        print(f"⏱️  Duration:       {total_time:.2f}s")
        print(
            f"👥 Clients Created: {self.stats['clients_created']} (Failed: {self.stats['clients_failed']})"
        )
        print(
            f"📁 Cases Created:   {self.stats['cases_created']} (Failed: {self.stats['cases_failed']})"
        )

        if self.stats["latencies"]:
            avg_lat = sum(self.stats["latencies"]) / len(self.stats["latencies"])
            max_lat = max(self.stats["latencies"])
            print(f"⚡ Avg Latency:     {avg_lat * 1000:.2f}ms")
            print(f"🐢 Max Latency:     {max_lat * 1000:.2f}ms")

        if self.stats["errors"]:
            print("\n❌ Recent Errors:")
            for err in self.stats["errors"][:5]:
                print(f"  - {err}")
        print("=" * 50 + "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="CRM Stress Tester")
    parser.add_argument("--url", default=DEFAULT_URL, help="Backend API URL")
    parser.add_argument("--key", default=DEFAULT_KEY, help="Admin API Key")
    parser.add_argument("--clients", type=int, default=50, help="Number of clients to create")
    parser.add_argument("--cases", type=int, default=2, help="Cases per client")
    parser.add_argument("--concurrency", type=int, default=10, help="Concurrent requests")
    parser.add_argument("--local", action="store_true", help="Use localhost defaults")

    args = parser.parse_args()

    url = "http://localhost:8080" if args.local else args.url

    tester = CRMStressTester(url, args.key, args.concurrency)
    asyncio.run(tester.run(args.clients, args.cases))
